### ISSUE TITLE
glimpse output not visible in qtconsole

### ISSUE THREAD

**Issue by mr-majkel** [pwwang/datar#117]
Hi,

first of all thanks for the great package! Working with data in Python is again comfortable:).

My issue is with recently added `glimpse()` function. When I am running the code in qtconsole I'm getting `<IPython.core.display.HTML object>` with no output. I have tried changing various qtconsole options to make it appear, but without success. Is there an option to make the HTML object appear in qtconsole that I need to set? If it is not possible, than maybe we can add some kind of flag or option in datar itself to make the the output plain text as it is in the case of Ipython REPL run in terminal?

**Comment by pwwang** [comment]
Now `datar` detects the environment using `IPython.get_ipython()`. It is able to tell whether the code is running with IPyhton, but not able to distinguish notebook and qtconsole. Will let the environment choose which display function to use (`._repr_html_()` for notebook, and `.__repr__()` otherwise)

**Comment by pwwang** [comment]
Fixed by [v0.8.2](https://github.com/pwwang/datar/releases/tag/0.8.2)

Note that `glimpse` has been moved from `datar.base` to `datar.dplyr`
