### ISSUE TITLE
In VScode, the code will be masked as comments [QST] 

### ISSUE THREAD

**Issue by yuemolin** [pwwang/datar#173]
### Question about datar

Hi~
I'm currently switching from R to python, and I really like and appreciate the packages. But when I use it in vscode, it will be recognized as comments instead of code, which will make all the following code "grey", is there any way to solve this problem?  Thanks!
<img width="736" alt="image" src="https://user-images.githubusercontent.com/39358286/222264181-84f60d50-ac4b-4d2a-93d0-e0b2d59bf2e5.png">

**Comment by pwwang** [comment]
Confirmed. Will dig into it.

**Comment by pwwang** [comment]
It's not an actual bug but because of the type annotations about the return value of the registered function.

![image](https://user-images.githubusercontent.com/1188067/222607992-be19e240-763e-4673-983a-c3969f63813b.png)

Currently, we don't have the annotation for the return value of the function, and by default the function raises a `NotImplementedError`, so `Pylance` thinks the error is for sure to be raised, so the code after it will not be reached.

Will try to add return value annotations to those functions in the next patch version.

**Comment by pwwang** [comment]
Should be fixed by [0.11.2](https://github.com/pwwang/datar/releases/tag/0.11.2)

**Comment by yuemolin** [comment]
Thank you! I just updated and it works fine!
