### ISSUE TITLE
Porting more related `tidyverse` packages

### ISSUE THREAD

**Issue by GitHunter0** [pwwang/datar#25]
I believe your great initiative could be stronger if you join forces with [siuba](https://github.com/machow/siuba), which has the same philosophy, instead of building a new project from the ground up. What do you think about that?

**Comment by pwwang** [comment]
Thanks for the suggestion.

I talked to @machow a couple of weeks ago. These two packages are focusing on different aspects. `suiba` is more powerful with SQL-generating support; while `datar` is more stringent on following the original `dplyr` and family's API design. And `datar` is now pretty complete on porting all of the APIs from `dplyr`, `tidyr`, and `tibble`.

I have kept an eye on `suiba`'s development, too. You may check out some of my comments on issues of `suiba`.

**Comment by GitHunter0** [comment]
I get it, thank you for the clarification. I just wish users could use the same package for both purposes.

By the way, what other packages do you plan to port? `forcats` and `purrr` would be great additions

**Comment by pwwang** [comment]
Great mentions about `forcats`, `purrr` and even [`dbplyr`](https://dbplyr.tidyverse.org/), a `dplyr` backend for databases, which functions similarly as `suiba` does. And maybe other related packages. 

Maybe I would make it independent of `datar`, or optional to `datar` (i.e. to be installed via `pip install datar[dbplyr]`). Since the backend support ([https://github.com/pwwang/pipda](https://github.com/pwwang/pipda)) for the piping syntax is independent, they don't have to be bundled with `datar`.

I need to block out a period on my calendar to implement then, but obviously not in a near future.

Of course, contributions and PRs are welcome for those ideas.

**Comment by GitHunter0** [comment]
Yes, `dbplyr` would be fantastic too. Nice to know you are open to it. Thank you for the feedback

**Comment by pwwang** [comment]
You are absolutely welcome!

Leaving this open for future discussions and people who may be interested in this topic.
