### ISSUE TITLE
`rowwise() >> mutate()` takes a long time to execute

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#78]
`rowwise() >> mutate()`  takes a very long time to execute. 
My original test data was 4000 columns and  2000 rows(mostly zeroes)  and took about 24minutes to execute but with `sum(axis=1)` took a few seconds.  I try to replicate the issue with the `mtcars` dataset below.

Also I would like to keep the index so I can know which values the sum belong to but `rowwise() >> mutate()`  takes it away -  `sum(axis=1)` keeps the index

Lines of code to replicate:
```python
mt2 = mtcars.append(mtcars).append(mtcars).append(mtcars).append(mtcars)

mt2 >> rowwise() >> mutate(total = sum(c_across(everything())))

#compare to 
mt2.sum(axis=1)

```

In the example below  `rowwise() >> mutate()`   takes   844ms  and  `sum(axis=1)` 26ms
![rowwise_mutate](https://user-images.githubusercontent.com/61335136/153257883-c36acbd7-32c4-4d70-961e-9ff4268f8999.PNG)

**Comment by pwwang** [comment]
Yep, noticed. Thanks for reporting. Working on a "fast" version at `fast` branch.

**Comment by pwwang** [comment]
With `0.6.0`:

![image](https://user-images.githubusercontent.com/1188067/156964474-62fdabd4-8be6-44f7-8db9-82d6617a8776.png)

![image](https://user-images.githubusercontent.com/1188067/156964511-f39bb098-b108-4154-a773-1459cb222f31.png)

It still takes longer, but the overhead was spent to parse the expressions, recycle the values, copy the original frames (so that the function is immutable). It uses `sum(axis=1)` to implement (`sum(c_across())`) under the hood, so the overhead is somehow fixed (won't increase while data gets bigger).

**Comment by rleyvasal** [comment]
I can confirm the timing of datar's `rowwise() >> mutate()` is very similar to that of `sum(axis)`- even when the data size increases.

Thanks @pwwang !

**Comment by pwwang** [comment]
Thanks for checking out.
You can also use `datar.base.row_sums()` (ported from `rowSums()` in `R`) in  this specific case to have less overhead that spent in assembling the frame from `c_across()`.
